# Site settings
title: Steve Hill
email: steve@stevehill.xyz
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Steve Hill.
  
  Here, you'll find occasional blog posts about technology,
  development, games and space travel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.stevehill.xyz" # the base hostname & protocol for your site
twitter_username: SteveHill1981
github_username:  stevehill1981

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
  categories:
    output: true
    permalink: /categories/:path/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "_categories"
    values:
      layout: "category"
